<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE help [
<!ENTITY lt "#38;#60;">
<!ENTITY gt "&#62;">
<!ENTITY amp "&#38;#38;">
<!ELEMENT help (name , synopsis , description* , arguments+ , outputs* , example* , bugs* , references* , reporting* , see-also*)*>
<!ELEMENT name (#PCDATA)>
<!ELEMENT synopsis (#PCDATA)>
<!ELEMENT description (#PCDATA)>
<!ELEMENT arguments (positional* , required-flagged* , optional-flagged*)*>
<!ELEMENT positional (intro* , argument* , explanation*)*>
<!ELEMENT required-flagged (intro* , argument* , explanation*)*>
<!ELEMENT optional-flagged (intro* , argument* , explanation*)*>
<!ELEMENT intro (#PCDATA)>
<!ELEMENT argument (#PCDATA)>
<!ELEMENT explanation (#PCDATA)>
<!ELEMENT outputs (output* , explanation*)>
<!ELEMENT output (#PCDATA)>
<!ELEMENT example (#PCDATA)>
<!ELEMENT bugs (#PCDATA)>
<!ELEMENT references (#PCDATA)>
<!ELEMENT reporting (#PCDATA)>
<!ELEMENT see-also (#PCDATA)>
]>

<help>
  <name>mri_warp_concat</name>
  <synopsis>mri_warp_concat [options] warp1.m3z warp2.m3z out.m3z</synopsis>
  <description>This program concatenates two non-linear warps (m3z format only). The positional input arguments should be in the same order in which the individual warps would be applied to a volume.</description>
  <arguments>
    <positional>
      <argument>warp1</argument>
      <explanation>input warp (m3z) that would be applied to scan first</explanation>
      <argument>warp2</argument>
      <explanation>input warp (m3z) that would be applied to scan second</explanation>
      <argument>out</argument>
      <explanation>concatenated output warp</explanation>
    </positional>
    <required-flagged>
      <intro>None</intro>
    </required-flagged>
    <optional-flagged>
      <intro>None</intro>
    </optional-flagged>
  </arguments>
</help>
